version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: pwd
  test-e2e-login:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install && cd ./test-e2e && npm install
      - run:
          name: Addittional step
          command: pwd
      - run:
          name: Running Tests
          command: |
            export NODE_OPTIONS=--max_old_space_size=4096
            export CUCUMBER_TAG='@login'
            export RANDOM_STRING='testing1'
            npm run test-e2e:browserstack
      - run:
          name: Save test results
          command: |
                  tar -czvf test-e2e-login.tar.gz test-e2e/target/site/serenity
                  tar -czvf logs.tar.gz /home/circleci/.npm/_logs/
                  mv logs.tar.gz test-e2e/target/logs.tar.gz
                  mv test-e2e-login.tar.gz test-e2e/target/test-e2e-login.tar.gz
          when: on_fail
      - store_artifacts:
          path: test-e2e/target

  test-e2e-account-creation:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install && cd ./test-e2e && npm install

      - run:
          name: Running Tests
          command: |
            export NODE_OPTIONS=--max_old_space_size=4096
            export CUCUMBER_TAG='@accountCreation'
            export RANDOM_STRING='testing2'
            npm run test-e2e:browserstack
      - run:
          name: Save test results
          command: |
            tar -czvf test-e2e-account-creation.tar.gz test-e2e/target/site/serenity
            tar -czvf logs.tar.gz /home/circleci/.npm/_logs/
            mv logs.tar.gz test-e2e/target/logs.tar.gz
            mv test-e2e-account-creation.tar.gz test-e2e/target/test-e2e-account-creation.tar.gz
          when: on_fail
      - store_artifacts:
          path: test-e2e/target

  test-e2e-account-recovery-via-magic-recovery-code:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install && cd ./test-e2e && npm install

      - run:
          name: Running Tests
          command: |
            export NODE_OPTIONS=--max_old_space_size=4096
            export CUCUMBER_TAG='@magicRecovery'
            export RANDOM_STRING='testing3'
            npm run test-e2e:browserstack
      - run:
          name: Save test results
          command: |
            tar -czvf test-e2e-account-recovery-via-magic-recovery-code.tar.gz test-e2e/target/site/serenity
            tar -czvf logs.tar.gz /home/circleci/.npm/_logs/
            mv logs.tar.gz test-e2e/target/logs.tar.gz
            mv test-e2e-account-recovery-via-magic-recovery-code.tar.gz test-e2e/target/test-e2e-account-recovery-via-magic-recovery-code.tar.gz
          when: on_fail
      - store_artifacts:
          path: test-e2e/target

  test-e2e-account-recovery-via-secret-key:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install && cd ./test-e2e && npm install

      - run:
          name: Running Tests
          command: |
            export NODE_OPTIONS=--max_old_space_size=4096
            export CUCUMBER_TAG='@secretRecovery'
            export RANDOM_STRING='testing4'
            npm run test-e2e:browserstack
      - run:
          name: Save test results
          command: |
            tar -czvf test-e2e-account-recovery-via-secret-key.tar.gz test-e2e/target/site/serenity
            tar -czvf logs.tar.gz /home/circleci/.npm/_logs/
            mv logs.tar.gz test-e2e/target/logs.tar.gz
            mv test-e2e-account-recovery-via-secret-key.tar.gz test-e2e/target/test-e2e-account-recovery-via-secret-key.tar.gz
          when: on_fail
      - store_artifacts:
          path: test-e2e/target
workflows:
  version: 2
  build_and_test_e2e_local_or_remote-e2e:
    jobs:
      - build
      - test-e2e-login
      - test-e2e-account-creation
      - test-e2e-account-recovery-via-magic-recovery-code
      - test-e2e-account-recovery-via-secret-key
